Fix set initial desktop state even if local browser state does not exist
MetaMask/metamask-desktop pull request #285
Opened 2022-11-30 11:18 UTC by OGPoyraz

## Overview 
This PR aims to fix an issue in the pairing flow.

Reproduce steps are [mentioned in the issue](https://github.com/MetaMask/desktop/issues/213).

2022-11-30 14:38 UTC, bergarces approved these changes

2022-11-30 16:03 UTC, cryptotavares approved these changes

2022-11-30 17:11 UTC, cryptotavares requested changes
This is what I think that is happening:
1. when shutting down the desktop app without removing connection, the desktop app is not removing the sate
2. then when restarting the app, it will be able to get the desktop controller state, although that state should not be valid. It is tricking the desktop app into thinking that it is paired, when it actually is not. see - https://github.com/MetaMask/desktop/blob/main-desktop/packages/app/src/app/desktop-app.ts#L97-L98
3. then when clicking on the remove connection button, the rawState is wiped out - https://github.com/MetaMask/desktop/blob/main-desktop/packages/app/src/app/desktop-app.ts#L78-L81
3.1 however the app is not restarted, as the disable connection listener is not registered. That listener is only registered once we have an new websocket connection - https://github.com/MetaMask/desktop/blob/main-desktop/packages/app/src/app/desktop-app.ts#L136-L146
4. Now as the app is not restarted, the background logic is not re-initialized, which means that the MetaMaskControllers state is never re-initialized. And because of that we end up with the local browser state empty.

Blocking this current fix, as we need to have a deeper investigation on what are the implications of having no local state when pairing (probably none for now, as we will override the desktop state with the extension state.. but I cannot be sure on the controllers internal logic).

2022-11-30 20:00 UTC, cryptotavares approved these changes
looks good ✅

2022-12-01 09:55 UTC, vinistevam approved these changes

2022-12-01 11:46 UTC, merged